databases:
  - name: mydb
    plan: free
    databaseName: mydb
    user: appuser

services:
  - type: web
    name: app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase: { name: mydb, property: host }
      - key: DB_PORT
        fromDatabase: { name: mydb, property: port }
      - key: DB_NAME
        fromDatabase: { name: mydb, property: database }
      - key: DB_USER
        fromDatabase: { name: mydb, property: user }
      - key: DB_PASSWORD
        fromDatabase: { name: mydb, property: password }
      - key: SPRING_KAFKA_BOOTSTRAP_SERVERS
        sync: false   # you enter this in the dashboard